### ISSUE TITLE
Error: listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by Wenxixx** [rdmclin2/weixin_server#1]
weixin_server git:(master) make run     
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1239:19)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at Function.app.listen (/Users/iSteven/iSteven/Github/weixin/weixin_server/node_modules/express/lib/application.js:531:24)
    at Object.<anonymous> (/Users/iSteven/iSteven/Github/weixin/weixin_server/bin/www:7:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by rdmclin2** [comment]
Try to change port to > 1024, such as 3000.

**Comment by Tracydeng** [comment]
改端口后服务起了，但是在微信配置服务时token验证不通过
